"""Subclass of FrameVolumes, which is generated by wxFormBuilder."""

import wx
import guiperfumes
import AcessandoBD
import wx.xrc
import wx.grid

# Implementing FrameVolumes
class FrameVolumes(guiperfumes.FrameVolumes):
	def __init__( self, parent ):
		guiperfumes.FrameVolumes.__init__( self, parent )
		self.atualizarGrid()
# Handlers for FrameVolumes events.
	def adicionarVolumes( self, event ):
		nome=self.txtNome.GetValue() #Recupera o conteúdo da caixa de texto
		AcessandoBD.inserirVolume(nome) #Chama a função inserir essencia do arquivo AcessandoBD.py
		#Exibe uma mensagem ao usuário confirmado o sucesso na inserção
		wx.MessageBox(message="Volume Inserido com Sucesso",caption="SisPerfumes",style=wx.OK,parent=self)
		self.atualizarGrid()#Atualiza o grid com a relação de volumes
	def fecharFrame( self, event ):
		self.Show(False)
	#Essa função é chamada quando o usuário edita o conteúdo de uma célula do meu grid
	def atualizarVolume( self, event ):
		nome_volume=self.gridVolumes.GetCellValue(event.GetRow(),event.GetCol()) #Recupera o nome do volume editado
		if (nome_volume): #Se o conteúdo não for vazio, faça
			id_volume=int(self.gridVolumes.GetCellValue(event.GetRow(),0))#Pegue na linha editada, o conteúdo da primeira coluna
			AcessandoBD.atualizarEssencia(id_volume,nome_volume) #Chame a função para atualizar um volume
			wx.MessageBox(message="Volume Atualizado com Sucesso",caption="SysPerfumes",style=wx.OK,parent=self)
	def atualizarGrid(self):
		if (self.gridVolumes.GetNumberRows()>0):
			self.gridVolumes.DeleteRows(0,self.gridVolumes.GetNumberRows()) #Limpa a tabela
		volumes=AcessandoBD.listarVolume() #Chama a função listar essencias, retornando a lista de volumes existentes
		for volume in volumes:
			self.gridVolumes.AppendRows(1)#Adiciona uma linha em branco
			self.gridVolumes.SetCellValue(self.gridVolumes.GetNumberRows()-1,0,str(volume[0])) #adicione o id do volume
			self.gridVolumes.SetCellValue(self.gridVolumes.GetNumberRows() - 1, 1, volume[1]) #adiciona o nome do volume
