"""Subclass of FrameMarcas, which is generated by wxFormBuilder."""

import wx
import ProjSisPerfumes

# Implementing FrameMarcas
class ProjSisPerfumesFrameMarcas( ProjSisPerfumes.FrameMarcas ):
	def __init__( self, parent ):
		ProjSisPerfumes.FrameMarcas.__init__( self, parent )

	# Handlers for FrameMarcas events.
	def fecharFrame( self, event ):
		# TODO: Implement fecharFrame
		pass

	def adicionarMarca( self, event ):
		# TODO: Implement adicionarMarca
		pass

	def atualizarMarca( self, event ):
		# TODO: Implement atualizarMarca
		pass


