"""Subclass of FrameEssencias, which is generated by wxFormBuilder."""

import guiperfumes
import FrameEssencias

# Implementing FrameEssencias
class ProjSisPerfumesFrameEssencias( guiperfumes.FrameEssencias ):
	def __init__( self, parent ):
		guiperfumes.FrameEssencias.__init__( self, parent )

	# Handlers for FrameEssencias events.
	def adicionarEssencia( self, event ):
		FrameEssencias.FrameEssencias.adicionarEssencia(self.txtNome, event)


	def atualizarEssencia( self, event ):
		FrameEssencias.FrameEssencias.atualizarEssencia(self.txtNome, event)


