"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import guiperfumes
import ProjSisPerfumesFrameMarcas
import ProjSisPerfumesFrameEssencias
import ProjSisPerfumesFrameFixacoes
import ProjSisPerfumesFrameVolumes
import ProjSisPerfumesFramePerfumesGrid


# Implementing FramePrincipal
class ProjSisPerfumesFramePrincipal( guiperfumes.FramePrincipal ):
	def __init__( self, parent ):
		guiperfumes.FramePrincipal.__init__( self, parent )

	# Handlers for FramePrincipal events.
	def abrirMarcas( self, event ):
		frameMarcas = ProjSisPerfumesFrameMarcas.ProjSisPerfumesFrameMarcas(None)
		frameMarcas.Show(True)

	def abrirEssencias( self, event ):
		frameEssencias = ProjSisPerfumesFrameEssencias.ProjSisPerfumesFrameEssencias(None)
		frameEssencias.Show(True)

	def abrirFixacoes( self, event ):
		frameFixacoes = ProjSisPerfumesFrameFixacoes.ProjSisPerfumesFrameFixacoes(None)
		frameFixacoes.Show(True)

	def abrirVolume( self, event ):
		frameVolumes = ProjSisPerfumesFrameVolumes.ProjSisPerfumesFrameVolumes(None)
		frameVolumes.Show(True)

	def abrirPerfumes( self, event ):
		framePerfumesGrid = ProjSisPerfumesFramePerfumesGrid.ProjSisPerfumesFramePerfumesGrid(None)
		framePerfumesGrid.Show(True)

	def abrirPerfumesEssencia( self, event ):

		pass

	def abrirSobre( self, event ):

		pass


	def sair( self, event ):
		self.Show(False)


