"""Subclass of FramePrincipal, which is generated by wxFormBuilder."""

import ProjSisPerfumes

# Implementing FramePrincipal
class ProjSisPerfumesFramePrincipal( ProjSisPerfumes.FramePrincipal ):
	def __init__( self, parent ):
		ProjSisPerfumes.FramePrincipal.__init__( self, parent )

	# Handlers for FramePrincipal events.
	def abrirFrameMarcas( self, event ):
		event.GetEventObject()

	def abrirFrameEssencias( self, event ):
		event.GetEventObject()

	def abrirFrameFixacoes( self, event ):
		event.Skip()

	def abrirFrameVolumes( self, event ):
		event.Skip()

	def abrirFrammePerfumes( self, event ):
		event.Skip()

	def abrirFramePerfumesEssencia( self, event ):
		event.Skip()

	def abrirSobre( self, event ):
		event.Skip()

	def abrirSair( self, event ):
		event.Skip()
