"""Subclass of FrameMarcas, which is generated by wxFormBuilder."""

import guiperfumes
import FrameMarca

# Implementing FrameMarcas
class ProjSisPerfumesFrameMarcas( guiperfumes.FrameMarcas ):
	def __init__( self, parent ):
		guiperfumes.FrameMarcas.__init__( self, parent )

	# Handlers for FrameMarcas events.
	def fecharFrame( self, event ):
		guiperfumes.FrameMarcas.fecharFrame(self, event)

	def adicionarMarca( self, event ):
		FrameMarca.FrameMarca.adicionarMarca(self.txtNome, event)

	def atualizarMarca( self, event ):
		FrameMarca.FrameMarca.atualizarMarca(self.txtNome, event)



