"""Subclass of FramePerfumesGrid, which is generated by wxFormBuilder."""

import wx
import ProjSisPerfumes

# Implementing FramePerfumesGrid
class ProjSisPerfumesFramePerfumesGrid( ProjSisPerfumes.FramePerfumesGrid ):
	def __init__( self, parent ):
		ProjSisPerfumes.FramePerfumesGrid.__init__( self, parent )

	# Handlers for FramePerfumesGrid events.
	def adicionarPerfume( self, event ):
		# TODO: Implement adicionarPerfume
		pass

	def salvarPerfume( self, event ):
		# TODO: Implement salvarPerfume
		pass


