"""Subclass of FrameFixacoes, which is generated by wxFormBuilder."""

import wx
import ProjSisPerfumes

# Implementing FrameFixacoes
class ProjSisPerfumesFrameFixacoes( ProjSisPerfumes.FrameFixacoes ):
	def __init__( self, parent ):
		ProjSisPerfumes.FrameFixacoes.__init__( self, parent )

	# Handlers for FrameFixacoes events.
	def adicionarFixacao( self, event ):
		# TODO: Implement adicionarFixacao
		pass

	def atualizarFixacao( self, event ):
		# TODO: Implement atualizarFixacao
		pass


