"""Subclass of FrameVolumes, which is generated by wxFormBuilder."""

import wx
import ProjSisPerfumes

# Implementing FrameVolumes
class ProjSisPerfumesFrameVolumes( ProjSisPerfumes.FrameVolumes ):
	def __init__( self, parent ):
		ProjSisPerfumes.FrameVolumes.__init__( self, parent )

	# Handlers for FrameVolumes events.
	def adicionarVolume( self, event ):
		# TODO: Implement adicionarVolume
		pass

	def atualizarMarca( self, event ):
		# TODO: Implement atualizarMarca
		pass


