"""Subclass of FrameEssencias, which is generated by wxFormBuilder."""

import wx
import ProjSisPerfumes

# Implementing FrameEssencias
class ProjSisPerfumesFrameEssencias( ProjSisPerfumes.FrameEssencias ):
	def __init__( self, parent ):
		ProjSisPerfumes.FrameEssencias.__init__( self, parent )

	# Handlers for FrameEssencias events.
	def adicionarEssencia( self, event ):
		# TODO: Implement adicionarEssencia
		pass

	def atualizarMarca( self, event ):
		# TODO: Implement atualizarMarca
		pass


