"""Subclass of FrameVolumes, which is generated by wxFormBuilder."""

import guiperfumes
import FrameVolumes

# Implementing FrameVolumes
class ProjSisPerfumesFrameVolumes( guiperfumes.FrameVolumes ):
	def __init__( self, parent ):
		guiperfumes.FrameVolumes.__init__( self, parent )

	# Handlers for FrameVolumes events.
	def adicionarVolume( self, event ):
		FrameVolumes.FrameVolumes.adicionarVolume(self.txtNome, event)

	def atualizarMarca( self, event ):
		FrameVolumes.FrameVolumes.atualizarVolume(self.txtNome, event)


